###
GET http://localhost:9200
Accept: application/json

###
GET {{host}}:{{port}}/?pretty=true
Accept: application/json

###
PUT {{host}}:{{port}}/get-together/_doc/1?pretty
content-type: application/json

{
  "name": "Elasticsearch Denver",
  "organizer": "Lee"
}

###
GET http://localhost:9200/get-together/_mapping

###
GET http://localhost:9200/_cat/indices?v

###
POST {{host}}:{{port}}/get-together/_search
Content-Type: application/json

{
  "query": {
    "match_all": {}
  }
}

###
GET {{host}}:{{port}}/get-together/_search?q=name:elasticsearch
Content-Type: application/json

###
GET {{host}}:{{port}}/get-together/_search
Content-Type: application/json

{
  "query": {
    "query_string": {
      "query": "elasticsearch san francisco",
      "default_field": "name",
      "default_operator": "AND"
    }
  }
}

###
GET {{host}}:{{port}}/get-together/_search?from=1&size=10&sort=created_on:asc&_source=name,created_on&q=name:elasticsearch

###
GET {{host}}:{{port}}/get-together/_search
Content-Type: application/json

{
  "query": {
      "match_all": {}
    },
  "from": 1,
  "size": 10
}

###
GET {{host}}:{{port}}/get-together/_search
Content-Type: application/json

{
  "query": {
    "match_all": {}
  },
  "_source": ["name", "created_on", "event.*"]
}

###
GET {{host}}:{{port}}/get-together/_search
Content-Type: application/json

{
  "query": {
    "match_all": {}
  },
"_source": ["name", "organizer", "description"],
  "sort": [
      {"created_on": "asc"}
      ]
}

###
GET {{host}}:{{port}}/get-together/_search
Content-Type: application/json

{
  "query": {
    "bool": {
          "must": [
            {"match": {"event.title": "Hadoop"}}
          ],
          "filter": {
            "term": {
              "event.host": "andy"
            }
          }
        }
  }
}

###
POST {{host}}:{{port}}/get-together/_search
Content-Type: application/json

{
  "query": {
    "match_all": {}
  }
}

###
POST {{host}}:{{port}}/get-together/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "filter": {
        "term": {"name": "elasticsearch"}
      }
    }
  }
}

###
POST {{host}}:{{port}}/get-together/_search
Content-Type: application/json

{
  "query": {
    "query_string": {
      "query": "nosql"
    }
  }
}

###
POST {{host}}:{{port}}/get-together/_search
Content-Type: application/json

{
  "query": {
    "query_string": {
      "default_field": "description",
      "query": "nosql"
    }
  }
}

###
POST {{host}}:{{port}}/get-together/_search
Content-Type: application/json

{
  "query": {
    "terms": {
      "tags": ["elasticsearch", "hadoop", "lucene"]
    }
  },
  "_source": ["name", "tags"]
}

###
POST {{host}}:{{port}}/get-together/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "should": [
        {"terms":  {"tags": ["elasticsearch", "hadoop", "lucene"]}}
      ],
      "minimum_should_match": 1
    }
  }
}